name = "cloudflare-webmail"
main = "src/index.ts"
compatibility_date = "2025-10-11"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "webmail-db"
database_id = "e8801a87-06b0-44e4-910c-4a55c3742958"

[[r2_buckets]]
binding = "ATTACHMENTS"
bucket_name = "webmail-attachments"
preview_bucket_name = "webmail-attachments"

[[ratelimits]]
name = "LOGIN_RATE_LIMITER"
namespace_id = "41001"
simple = { limit = 9, period = 60 }

[vars]
OCI_EMAIL_ENDPOINT = "https://cell0.submit.email.ca-montreal-1.oci.oraclecloud.com"
OCI_EMAIL_CONTROL_ENDPOINT = ""
OCI_EMAIL_COMPARTMENT_OCID = "ocid1.tenancy.oc1..aaaaaaaanl6exevvdu277x7w6fc7ac3lkdv6ufox36utlv6gsc4rcvqjktda"
